FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

RUN apt install -y git python-pip
RUN git clone https://github.com/nod-ai/llama.git
RUN cd llama && pip install -r requirements.txt 
RUN cd llama && pip install -e . 

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
