FROM pytorch/pytorch:latest

RUN apt update && apt install -y git python3-pip
RUN git clone https://github.com/nod-ai/llama.git
RUN cd llama && pip install -r requirements.txt --break-system-packages
RUN cd llama && pip install -e . --break-system-packages

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
