FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

RUN git clone https://github.com/nod-ai/llama.git
RUN cd llama && pip install -r requirements.txt --break-system-packages
RUN cd llama && pip install -e . --break-system-packages

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
