FROM nvidia/cuda:12.1.1-devel-ubuntu20.04

RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y git python3-pip mc wget libopenblas-dev

#install llama.cpp gpu version
RUN git clone https://github.com/ggerganov/llama.cpp
RUN cd llama.cpp && make LLAMA_OPENBLAS=1

#load default model
RUN cd llama.cpp/models && wget https://huggingface.co/Pi3141/alpaca-native-13B-ggml/resolve/main/ggml-model-q8_0.bin

COPY run /root/run
RUN chmod 744 /root/run*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
