FROM pytorch/pytorch:latest

RUN apt update && apt install -y git python3-pip

# install nod-ia llama
RUN git clone https://github.com/nod-ai/llama.git
RUN cd llama && pip install -r requirements.txt 
RUN cd llama && pip install -e . 

# install lit-llama
RUN git clone https://github.com/Lightning-AI/lit-llama
RUN cd lit-llama && pip install -r requirements.txt 

COPY run /root/run
RUN chmod 744 /root/run*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
