FROM twobombs/thereminq-llama

#fetch llama.cpp
RUN git clone https://github.com/ggerganov/llama.cpp
RUN cp -r llama.cpp llama-openblas
RUN cp -r llama.cpp llama-cublas
RUN cp -r llama.cpp llama-clblast

# build all versions
RUN cd llama.cpp && make -j
RUN cd llama-openblas && cmake . && make LLAMA_OPENBLAS=1 all
RUN cd llama-cublas && cmake -DGGML_CUBLAS=ON . && make LLAMA_CUBLAS=1 all
RUN cd llama-clblast && cmake -DGGML_CLBLAST=ON . && make LLAMA_CLBLAST=1 all

RUN ln -s /orca_mini_v2_13b.ggmlv3.q2_K.bin /llama-cpp/models/orca_mini_v2_13b.ggmlv3.q2_K.bin
RUN ln -s /orca_mini_v2_13b.ggmlv3.q2_K.bin /llama-cublas/models/orca_mini_v2_13b.ggmlv3.q2_K.bin
RUN ln -s /orca_mini_v2_13b.ggmlv3.q2_K.bin /llama-clblast/models/orca_mini_v2_13b.ggmlv3.q2_K.bin
RUN ln -s /orca_mini_v2_13b.ggmlv3.q2_K.bin /llama-openblas/models/orca_mini_v2_13b.ggmlv3.q2_K.bin

# test build
RUN cd llama.cpp && ./main -m /orca_mini_v2_13b.ggmlv3.q2_K.bin -p "explain the negative energy spike when teleporting a qubit according to ER=EPR" -n 512

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
