#!/bin/bash
# this run will store and verify 100 qcircuit tensors at 30x30 qubits depp and wide, measure and store their result as well
# this is a test to look for runtime visuals in thereminq-bonsai and processing in thereminq-llama
#
cd qrack128/_build && ./benchmarks -optimal --single --max-qubits=30 --benchmark-depth=30 test_circuit_t_nn_generate_and_load --measure-output=/var/log/qrack/"test_circuit_t_nn_$(date +%F_%R_%S).log"
