#!/bin/bash

# qrack_cl_precompile
/qrack/_build/qrack_cl_precompile

# start mongod
mongod &

# start chatui
cd /chat-ui && npm run dev &

# start webui
cd  /text-generation-webui && python3 server.py --listen --share --trust-remote-code --gradio-auth thereminq:00000000 &

# when fail do not stop container ( debug )
tail -f /dev/null
