#!/bin/bash

# X-run script
rm /tmp/.X0-lock
Xvfb :0 -screen 0 2560x1440x24+32 -ac &
export DISPLAY=:0&&startxfce4 &
sleep 10
x0vncserver -display :0 -passwordfile ~/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900 &
service xrdp start && xrdp &

export DISPLAY=:0&&xterm -e "xset s off" &
export DISPLAY=:0&&xterm -bg black -fg white -e "neofetch && tail -f /dev/null" &
export DISPLAY=:0&&exo-open --launch TerminalEmulator &

# show system config in logs
nvidia-smi
ifconfig

./webui.sh -f --skip-torch-cuda-test --no-download-sd-model &

sleep 10

# precompile qrack kernels
./qrack/_build/qrack_cl_precompile

tail -f /dev/null
