#!/bin/bash

# qrack_cl_precompile
/qrack/_build/qrack_cl_precompile &

# elastic
sudo -u elasticsearch /usr/share/elasticsearch/bin/elasticsearch &
sleep 10
cd /usr/share/kibana/bin && ./kibana --allow-root &

tail -f /dev/null
