#!/bin/bash

# show system config in logs
nvidia-smi
ifconfig

# start OpenAI API simulator
python3 -m llama_cpp.server --model /wizardmath-7b-v1.0.Q2_K.gguf &

sleep 10

# precompile qrack kernels
./qrack/_build/qrack_cl_precompile

tail -f /dev/null
