#!/bin/bash

# qrack_cl_precompile
/qrack/_build/qrack_cl_precompile

# start OpenAI API simulator
python3 -m llama_cpp.server --model /wizardmath-7b-v1.0.Q2_K.gguf &

# start sparky

export SPARK_HOME=/opt/spark
export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# spark start
./opt/spark/sbin/start-master.sh &

sleep 10

# start worker node
./opt/spark/sbin/start-slave.sh spark://$HOSTNAME:7077 &

sleep 10

./opt/spark/bin/spark-shell 

tail -f /dev/null
