FROM twobombs/thereminq-llama:opencl

RUN apt update && apt install -y default-jre && apt clean

# do spark things
RUN wget https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz && tar xvf spark-3.5.0-bin-hadoop3.tgz && mv spark-3.5.0-bin-hadoop3/ /opt/spark && rm spark-3.5.0-bin-hadoop3.tgz

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-spark
