FROM twobombs/thereminq-llama

RUN pip3 install git+https://github.com/amazon-science/chronos-forecasting.git && pip cache purge

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
