FROM twobombs/thereminq-llama

# agent will require quantum dependancies

# install runtime requirements
# to speed up the agent process
RUN pip3 install --upgrade pip
RUN pip3 install pyqrack  && pip cache purge

# Install Qiskit libaries
RUN pip3 install qiskit[all] qiskit-qrack-provider && pip cache purge

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience && pip cache purge

# install IQM connectors and libary
RUN pip3 install qiskit-iqm && pip cache purge

# install cirq and mitiq
RUN pip3 install cirq[all] mitiq[all] && pip cache purge

# install open-interpreter web UI
RUN git clone --depth=1 https://github.com/blazzbyte/OpenInterpreterUI.git
RUN cd OpenInterpreterUI && pip3 install -r requirements.txt && pip cache purge

# get AgentGPT - optional UI - in development 
RUN git clone --depth=1 https://github.com/reworkd/AgentGPT.git

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-agent
