FROM twobombs/thereminq-llama:opencl

# RUN apt install -y default-jre && apt clean

# orchestate placeholder

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-orchestrate
