FROM twobombs/thereminq-llama

#fetch llama.cpp
RUN git clone --depth=1 https://github.com/ggerganov/llama.cpp
RUN cp -r llama.cpp llama-openblas
RUN cp -r llama.cpp llama-cublas
RUN cp -r llama.cpp llama-clblast

#OpenCL integration 
#RUN CMAKE_ARGS="-DLLAMA_CLBLAST=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
$RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings

#CUDA integration default
RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings 

# build all versions
RUN cd llama.cpp && make -j
RUN cd llama-openblas && cmake . && make LLAMA_OPENBLAS=1 all
RUN cd llama-cublas && cmake -DGGML_CUBLAS=ON . && make LLAMA_CUBLAS=1 all
RUN cd llama-clblast && cmake -DGGML_CLBLAST=ON . && make LLAMA_CLBLAST=1 all

RUN ln -s wizardmath-7b-v1.1.Q2_K.gguf /llama.cpp/models/wizardmath-7b-v1.1.Q2_K.gguf
RUN ln -s wizardmath-7b-v1.1.Q2_K.gguf /llama-cublas/models/wizardmath-7b-v1.1.Q2_K.gguf
RUN ln -s wizardmath-7b-v1.1.Q2_K.gguf /llama-clblast/models/wizardmath-7b-v1.1.Q2_K.gguf
RUN ln -s wizardmath-7b-v1.1.Q2_K.gguf /llama-openblas/models/wizardmath-7b-v1.1.Q2_K.gguf

# test build
# RUN cd llama.cpp && ./main -m /llama.cpp/models/wizardmath-7b-v1.1.Q2_K.gguf -p "explain the negative energy spike when teleporting a qubit according to ER=EPR and devise a strategy to prove this thesis on a quantum computer" -n 512

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
