FROM twobombs/thereminq-llama

# agent will require quantum dependancies so we
# install pyqrack + couplings, runtime requirements
# to speed up the agent process
RUN pip3 install --upgrade qiskit-metal pyqrack
# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience
# Install Qiskit libaries
RUN pip3 install qiskit[visualization] qiskit-qrack-provider qiskit-aqua
# install IQM connectors and libary
RUN pip3 install qiskit-iqm 

# HF pip dependancies
RUN apt install -y python3-pip npm ipython3 python-is-python3 ffmpeg python3-venv libgl1 libglib2.0-0 && apt clean
RUN pip3 install --upgrade pip
RUN pip3 install huggingface_hub[hf_transfer] open-interpreter && pip cache purge

# install open-interpreter web UI
RUN git clone --depth=1 https://github.com/blazzbyte/OpenInterpreterUI.git
RUN cd OpenInterpreterUI && pip3 install -r requirements.txt && pip cache purge

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-agent
