FROM twobombs/thereminq-llama

# HF pip dependancies
RUN apt install -y python3-pip 
RUN pip3 install --upgrade pip
RUN pip3 install huggingface_hub[hf_transfer]

# install npm, reqs
RUN echo "deb http://security.ubuntu.com/ubuntu jammy-security main" | tee /etc/apt/sources.list.d/jammy-security.list
# RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
RUN chmod 744 /root/.nvm/nvm.sh && cd /root/.nvm && ./nvm.sh install 20 
# && node --version 
RUN apt update && apt install -y gnupg git-lfs && apt clean

# fetch build & setup webui
# RUN git clone --depth=1 --branch v1.7 https://github.com/oobabooga/text-generation-webui.git
RUN git clone --depth=1 https://github.com/oobabooga/text-generation-webui.git
RUN cp -r /text-generation-webui /text-generation-webui-cpu
RUN cd text-generation-webui && pip3 install --ignore-installed -r requirements.txt
RUN cd text-generation-webui-cpu && pip3 install --ignore-installed -r requirements_cpu_only.txt


ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-chatui
