FROM twobombs/thereminq-llama:opencl

RUN apt update && apt install -y default-jre ca-certificates curl gnupg && apt clean

# setup cassandra repo
RUN echo "deb https://debian.cassandra.apache.org 41x main" | tee -a /etc/apt/sources.list.d/cassandra.sources.list
RUN curl https://downloads.apache.org/cassandra/KEYS | apt-key add -

# install node req.
RUN mkdir -p /etc/apt/keyrings && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# install cassandra
RUN apt-get update && apt-get install cassandra nodejs ruby ruby-dev -y

# install cassandra-web
RUN git clone https://github.com/orzhaha/cassandra-web.git --depth=1
RUN cd /cassandra-web/client && npm i --force --legacy-peer-deps && npm run build

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

ENTRYPOINT /root/run-cassandra
