FROM twobombs/thereminq-llama:opencl

# RUN apt install -y default-jre && apt clean

# do opensearch things
RUN apt-get update && apt-get -y install lsb-release ca-certificates curl gnupg2
RUN curl -o- https://artifacts.opensearch.org/publickeys/opensearch.pgp | gpg --dearmor --batch --yes -o /usr/share/keyrings/opensearch-keyring
RUN echo "deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main" | tee /etc/apt/sources.list.d/opensearch-2.x.list
RUN apt-get update && apt-get install -y opensearch opensearch-dashboards && apt clean all

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-opensearch
