FROM twobombs/thereminq-llama
# get & set mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | tee /usr/share/keyrings/mongodb.gpg > /dev/null
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y mongodb-org && apt clean
RUN mkdir data && mkdir data/db

# HF pip dependancies
RUN apt install -y python3-pip npm ipython3 ffmpeg && apt clean
RUN pip3 install --upgrade pip
RUN pip3 install huggingface_hub[hf_transfer]

# install npm, reqs
RUN echo "deb http://security.ubuntu.com/ubuntu jammy-security main" | tee /etc/apt/sources.list.d/jammy-security.list
# RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
RUN chmod 744 /root/.nvm/nvm.sh && cd /root/.nvm && ./nvm.sh install 20 
# && node --version 
RUN apt update && apt install -y gnupg git-lfs && apt clean

# get chat ui webgui
RUN git clone --depth=1 https://github.com/oobabooga/text-generation-webui.git
RUN cp -r /text-generation-webui /text-generation-webui-cpu
RUN cd text-generation-webui && pip3 install --ignore-installed -r requirements.txt
RUN cd text-generation-webui-cpu && pip3 install --ignore-installed -r requirements_cpu_only.txt

# install CopperAI
COPY /misc/copperai.env /CopperAI/.env
RUN git clone https://github.com/athrael-soju/CopperAI.git && cd CopperAI && npm install

# install personal llm assistant
RUN git clone https://github.com/amirarsalan90/personal_llm_assistant && cd personal_llm_assistant && chmod install.sh 755 && ./install.sh

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-chatui
