FROM twobombs/thereminq-llama:spark

# install npm, mongodb + reqs
RUN echo "deb http://security.ubuntu.com/ubuntu jammy-security main" | tee /etc/apt/sources.list.d/jammy-security.list
# RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
RUN bash ./root/.nvm/nvm.sh install 20 && node --version 
RUN apt update && apt install -y gnupg && apt clean

RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | tee /usr/share/keyrings/mongodb.gpg > /dev/null
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y mongodb-org && apt clean

# fetch chat-ui
RUN git clone https://github.com/huggingface/chat-ui
RUN cd chat-ui && touch env.local && echo "MONGODB_URL=MONGODB_URL=mongodb://$HOSTNAME:27017" > env.local && npm install 
# && npm run dev

# fetch webui
RUN git clone https://github.com/oobabooga/text-generation-webui.git
RUN cd text-generation-webui && pip install -r requirements.txt

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-spark
